# Generated by Django 5.1.6 on 2025-03-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_payments"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="link",
            field=models.URLField(
                blank=True, max_length=400, null=True, verbose_name="ссылка на оплату"
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="session_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="id сессии"
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="payment_sum",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Укажите сумму платежа",
                max_digits=10,
                verbose_name="Сумма платежа",
            ),
        ),
    ]
