# Generated by Django 5.1.6 on 2025-02-25 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_payments"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payments",
        ),
    ]
