# Generated by Django 5.1.6 on 2025-03-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0008_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="amount",
            field=models.IntegerField(default=1000, verbose_name="цена"),
        ),
    ]
